const movies = [
    {
      id: 1,
      title: "The Diplomat",
      slug: "the-diplomat",
      genre: "Comedy",
      year: 2024,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABX7uyBNd44JK_89DNbFhn8EvZAt476IeB2M-s-9loGZhkC13WcusoONzVu2ttZ851SnGSMVUl-1hWEjETOLJgOsZeobTzVmxF5AVMdUDdwhdL4GaJsnnv3D12PfgEGnVy_Iq6j5vEswTT6KvxqeDPSCKomIdQk0FOxSwgXn01LS9r9JsOG4Q4vDHj4wCDiLJVdDKcLf100KTIoLCKIkWmTRfjev6Mu_6FNQF6xm1p-4lOfXttXSvVLK_KH_wwUf91ibEfjQ3BbHKeMsi98bQgqITK2ohQVACTIt3rKok8VS5J5KZ1j8yEfXo925KSUcJOgpAUNHDvXc6JGLXE_QI88FtDLuV2LYOvc5tIbzC6S9f8g.jpg?r=da9",
      description: "In the midst of an international crisis, Kate Wyler, a career diplomat, lands in a high-profile job for which she is not suited, with tectonic implications for her marriage and her political future.",
      rating: "A",
      actors: ["Keri Russell", "Rufus Sewell", "Ali Ahn"],
      director: "Debora Cahn",
      youtube_trailer: "https://youtu.be/LXXcRPmL7HE?si=nbD3H6NrL-FZJzA-"
    },
    {
      id: 2,
      title: "Bard of Blood",
      slug: "bard-of-blood",
      genre: "Action",
      year: 2024,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABXVhg5xNVsKIE8mqlro6FyftmcfwE0n_6AYHQAjS1rW2icCy-mm4yISO0ZXX-bjTKiP7mAKGAwhi-Otc8Q2oepIdbHmqk73QtPjbI0Xn8csmiIwQCxLcwqL3Z1yhDeGrfXfd.jpg?r=e35",
      description: "Ex communicated RAW agent Kabir Anand, a courageous analyst and a sleeper agent take on a covert mission in Balochistan when four Indian spies are captured; the mission soon turns south and Kabir must face his demons from the past.",
      rating: "A",
      actors: ["Emraan Hashmi","Emraan Hashmi","Sobhita Dhulipala"],
      director: "Ribhu Dasgupta",
      youtube_trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/uEE7HqPvqOg?si=NvI9yniTSbfeLWB6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'
      
    },
    {
      id: 3,
      title: "Cat",
      slug: "cat",
      genre: "Crime",
      year: 2022,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABWzZxDTtzuzqvb_EdGqVFVHWqdafBUuLpLFGdRj5W0fvdSZ4Oa2agTgerxQzQs3B9TjRJJ1z71voyzWGxqXeLceQpamvV8-KM51cYyEgeNVJBACUTp37RsJTPm9wNOalOAUY.jpg?r=e5a",
      description: "A former police informant is forced to become an informant again to save the life of his brother, which forces him to come to terms with his dark past.",
      rating: "A",
      actors: ["Randeep Hooda", "Abhishant Rana", "Suvinder Vicky"],
      director: "Balwinder Singh Janjua",
      youtube_trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/PLsF0sd6GiY?si=4VZhsrC1-Ogj2orE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'
    },
    {
      id: 4,
      title: "The Railway Men",
      slug: "the-railway-men",
      genre: "Drama",
      year: 2023,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABf5H92JqI4CcUzuhiyGnrNDY20Ft1VILzxXxkTN9cWnWny4mB3UREDTXMnHDYXWiRfZmJze7Cq4yJ7VOQznTJ9LXREaBFgsrowVAGnc9NmvDLyjbxURnam2G6gUKxx3Bl4A3.jpg?r=46c",
      description: "Inspired by true stories, this series is a gripping tale of extraordinary heroism demonstrated by the employees of the Indian Railways in Bhopal. They rose against all odds to save their fellow citizens on the night.",
      rating: "U/A 16+",
      actors: ["Madhavan", "Kay Kay Menon", "Divyendu Sharma"],
      director: "Shiv Rawail",
      youtube_trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/iD3TZ_Xxc14?si=4d_xhyqA55qnw7in" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'
    },
    {
      id: 5,
      title: "Meiyazhagan",
      slug: "meiyazhagan",
      genre: "Drama",
      year: 2024,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUHy8j4bPf6_OyfVZ5szL9z2OnIgoPQne5y-nZvTFIfOWqvCHWefftbGGHoxXPNgWo2WPyibVnSrefxkiQkbLx96row0eB1jmKjoLnT0ZoUREVvenO90ecG3MMj3KQs8NbqmBJFDDlaQgQUz_C3ATCPBGozOXxaYVT63TCsXbL7JC6VbhZIPAbwL_kvp5VxCvKJLbFcejkqKOuoEuLw4SxzDA3gvVn5LyyLEPCO8AuE_NNXc3cdfNXBJGPVcUhTzw9dzxuuWyxCEb0uQf5O2Ngo-3bWkaVBCPcjkVhPiIxaOmPKaO8nSxHO0O5HWUnaZWJgV7Nm52KdciJOIfpzofZ0.webp?r=b02",
      description: "A man's life is changed when he bumps into someone from his hometown in this moving Tamil-language drama; gentle scenes are occasionally punctuated by sporting threat and recollections of violence.",
      rating: "U/A 7+",
      actors: ["Karthi", "Arvind Swamy", "Sri Divya"],
      director: "C. Prem Kumar",
      youtube_trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Ahp840_aCoI?si=rlQ-4ij60my3gYRe" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'
    },
    // {
    //   id: 6,
    //   title: "",
    //   slug: "",
    //   genre: "",
    //   year: 2024,
    //   img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABTcvHMMSHeJ61ElsD1UE0D8yUNkZZMPSqp-qdadD8XseEv1LRprnenJXM3tGYIHJmvZDlLYJRf1GN0vXkmVixXCkYW95PaZNljNA4AfdnDTXoOQMu6ktdjBQeTSR_NBdaXZb.jpg?r=66c",
    //   description: "",
    //   rating: "",
    //   actors: [],
    //   director: "",
    //   youtube_trailer: ""
    // },
    // {
    //   id: 7,
    //   title: "",
    //   slug: "",
    //   genre: "",
    //   year: 2024,
    //   img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABW92yOB1rqnnCwaP_wQCT_zV11j-xy3mcOigSNapu1aPNLDnotOeRnVH6YpnhwYLJD3qYdWWLyT7vP8NIsgUK9JJhCShChNl9GpqNuBTHdUPvd-vhSAY42hpJ9zo7Wlh0P0NpK1kjvCjKPlg6g8s7_kCv33N2So_oz1pcMg0IgvhAHof-p7VWKq7ta0ug4gZNXeprLItuUZvXRm-5BqlJqvbABntc1GVjPVluBwx3IsC4_1pnvdMaP4Sz5KePmIL5njM3uhW7hMH_goriB6xBFG6KlCryc9o2sPi9QkzXdExHc9GHc-egoJ2LaPi7bptINEIQxyPAz1bOH-6ELTtR9RtBLr6kEvSQysS4xHJl4T2ooi3KLU.jpg?r=6d5",
    //   description: "",
    //   rating: "",
    //   actors: [],
    //   director: "",
    //   youtube_trailer: ""
    // },
    // {
    //   id: 8,
    //   title: "",
    //   slug: "",
    //   genre: "",
    //   year: 2024,
    //   img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABTeJHU_KCy6ygReSMC93Xl3Y727Kkht0emKLJ7EO4yAnAgGB7NmlveK3ggVuebY8NufhLDJ01oqlDz8RscCHDEoQmcOhg-IewGI.webp?r=f74",
    //   description: "",
    //   rating: "",
    //   actors: [],
    //   director: "",
    //   youtube_trailer: ""
    // },
    // {
    //   id: 9,
    //   title: "",
    //   slug: "",
    //   genre: "",
    //   year: 2024,
    //   img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABYN2mv23Y6ZLU0-zVitTr4_fTA8QkGB1yX-GloS9lDINY1ghS2wGuvV5XxrrJJKnMWOgGS1nthsWtvv-nG5EepH4Cwj7rleotTUi7o_8-R3eVRHF8w5yc4Bz417nmoNX8Uc-.jpg?r=8be",
    //   description: "",
    //   rating: "",
    //   actors: [],
    //   director: "",
    //   youtube_trailer: ""
    // },
    // {
    //   id: 10,
    //   title: "",
    //   slug: "",
    //   genre: "",
    //   year: 2024,
    //   img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfttqe53LJVE_giCp_NGuhsjyFEf6RG4VlC_OszSftbfV3VnZRWIxIcq8hzSOJ1FI7WbbV73ouCOO6PyZhrXZFq4yV6UmfdcEFW8bJ4zrmns_XNbKdYXpjvmaK-zkNipHNtI.jpg?r=24a",
    //   description: "",
    //   rating: "",
    //   actors: [],
    //   director: "",
    //   youtube_trailer: ""
    //   },    
  ];

export default movies;

