const movies = [
    {
      id: 1,
      title: "Do Patti",
      slug: "do-patti",
      genre: "Drama",
      year: 2023,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABQSlWCyhclaFgZ2H59Hn0Y3MoRoRS0s7OAd4qYi1rkLYDPC_iLcZoyW2MpWrIFO_-kZJbPIBG_E1Qq7D6jahrjN1ulqB8m-cWXS94c53_IZsH4OeAee79gBLpYjmGrXr1OGDTyF6GZtos2tlU4tMJW14E7O-bOE0ldX-UF_9nPdRpnzg3sCwOK-AbsCwPGT8ebfsOmeDyjEhf4B-pRS_Pprlyf6K9YDAXNf7DRf3LL9nDKn-uC8uE2RyrN0y9FhefAOQkl0LUSMJwoELqX1aqYUA7rkSu5KoRhhNjpEKIplCS6-YKpDDqEbYDQ.jpg?r=b7e",
      description: "Twin sisters harbouring deep secrets and a determined police inspector seeking to uncover the truth in an attempted murder case.",
      rating: "U/A 16+",
      actors: ["Kriti Sanon", "Kajol", "Brijendra Kala"],
      director: "Shashanka Ghosh",
      youtube_trailer: "url_to_trailer_of_do_patti"
    },
    {
      id: 2,
      title: "Meiyazhagan",
      slug: "meiyazhagan",
      genre: "Action",
      year: 2023,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABfuGU4RANNXOYEBwq3MWfyYbBxNB9AE7yqSJlDs06Jz9Y-CJo6uj605d5Rp-_jQb93-CaxjVzqApwT2W7YKdAIuXzL1RTtQMiBqXLLg5FMaih3HyUpWU7dCJT9JiT-zqtK9wIS5P0MJaYGrks5k7Tk9PaKb8yyO_kv2oW379Bvm_U2xz6nUlx5HL2i1xsTl1esu1Xy2-P0u1tIQnPpw6KoJEcJF_lYQ9f-IoOwyBj2iVbCVyMzOxorf_XNUkCjTXMktDq2UxccagQu3fuJqsuOxAGBJZ7g.webp?r=bb0",
      description : "A man's life is changed when he bumps into someone from his hometown in this moving Tamil-language drama; gentle scenes are occasionally punctuated by sporting threat and recollections of violence.",
      rating: "U/A 7+",
      actors: ["Karthi", "Arvind Swamy", "Sri Divya"],
      director: "Director Name",
      youtube_trailer: "url_to_trailer_of_meiyazhagan"
    },
    {
      id: 3,
      title: "Transformers: Rise of Beasts",
      slug: "transformers-rise-of-beasts",
      genre: "Action, Sci-Fi",
      year: 2023,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABSTdVJ-j32tTc1ZOSa5VwIi-M_U18symJeZqfSYikbL7ISbtrkcQmhvU-gQOs0yYwOVpnJAv1I5G-qq-587DXi4oMsQiqJVKtFpUe3T_vVyO1ngZD81NfsrYwApnQWy9_2phyEg3amiD_zME-MH5aNWq66u2dxX1KDgIlVKNlEICaSSbMttbm-ljaF6KazTzT0-oq9dDCH_sf9OqJZXqdrc7d95rhE7wu9dEnPQrxzZgL5JQFvS_qQsqOLPG-eHcZHlMSPJfY1VaFhbICUxw5yQsPvIP9A.webp?r=8f7",
      description : "A man's life is changed when he bumps into someone from his hometown in this moving Tamil-language drama; gentle scenes are occasionally punctuated by sporting threat and recollections of violence.",
      rating: "U/A 13+",
      actors: ["Anthony Ramos", "Dominique Fishback"],
      director: "Steven Caple Jr.",
      youtube_trailer: "url_to_trailer_of_transformers"
    },
    {
      id: 4,
      title: "Don't Move",
      slug: "dont-move",
      genre: "Horror, Thriller",
      year: 2023,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABWbr7WqVjKDb2JNjTpWVIBaTubfnPu4DKK4F2W09pDMrjD-O4BR4WhHT261SXvvQ0egTOtpT2WyoYXLR5kaFW3t-HYh5AFEOMBEY8UnT2p0icrhIGCceY_wc218sCa4U_-C9LJ0Us49OyoftCO0rs98zNBjrNIn1vJStWoe8KbIU_jMUsppbRUrzkZsULhK5x--PrEbSkC_ahypeozOvfCTdRpOizm0pCSRrc6bx6ZoKKq3cCZPhCiHb44M_h7TXP6rLm7pxpH5eOqe_6D_mEuWmNVWtv-Wlei_g4fQC36KHBmbOtnGTv_uG2A.jpg?r=7e5",
      description : "A man's life is changed when he bumps into someone from his hometown in this moving Tamil-language drama; gentle scenes are occasionally punctuated by sporting threat and recollections of violence.",
      rating: "U/A 16+",
      actors: ["Actor A", "Actor B"],
      director: "Director Name",
      youtube_trailer: "url_to_trailer_of_dont_move"
    },
    {
      id: 5,
      title: "Khel Khel Mein",
      slug: "khel-khel-mein",
      genre: "Comedy, Drama",
      year: 2024,
      img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABTgICg7Js9IueW62LJmTf5i85m_SY73M4nx9kRA3j1imXZLisY-OxN22MjUC27Shv_o364cVoHqCljYhGgH61tqeEGN9zzS6CRax9YIkGiPkaCtNNBOyYFlEqVGf21FjbcTspQspsAirdpFI-KsRL89O7hOLPCn90seurQBnKeTkST5byNQv7SNN_lmpHytEiU0AiYNTda0FmI6GHvp-GXYse7LmKo0ckoNZeQyt6BPUlh-eqH_BhwDxr76c4IcZSv0cf8xKMSJkCeNPVWsLg4GGzxBtbA.webp?r=580",
      description: "Revolves around a group of friends who gather for a dinner and end up revealing secrets about each other.",
      rating: "U/A 16+",
      actors: ["Akshay Kumar", "Ammy Virk", "Taapsee Pannu"],
      director: "Mudassar Aziz",
      youtube_trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/RKZJtoFoaQg?si=pISRa7qfhUrHLpjO" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>'
    },
    {
        id: 6,
        title: "Khel Khel Mein",
        slug: "khel-khel-mein",
        genre: "Comedy, Drama",
        year: 2024,
        img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABdx1g9P9R7r9Z3thByhk8Bv7lF6wXN6Y-5UxBXuerfOzSeza1CyYofxvx5qoDLzApZkTnOoKOh0l9zg1qamdS8Q8eZcMoTIcsEixav30Ac8aRMFpOt68ZQPL5JchWLXl9N8hYyv645C5zAc_XJcg5leyhqkfbhXq3RbVssVB7lueqz5i4Z5ixLfLj7Sin7NyHIdFFGEYBhPO37OCbRAoHn6nuJL0AqxNzNd-cYnTK2T_McBCTLX-h8TQrezuZrh_ndmwj1DLNOBdZKRvz5WP2bOizFIcG_9fz7gFWAaA-i_NZ9polm6utdxSxQ.jpg?r=63e",
        description: "Revolves around a group of friends who gather for a dinner and end up revealing secrets about each other.",
        rating: "U/A 16+",
        actors: ["Akshay Kumar", "Ammy Virk", "Taapsee Pannu"],
        director: "Mudassar Aziz",
        youtube_trailer: "url_to_trailer_of_khel_khel_mein"
      },
      {
        id: 7,
        title: "Khel Khel Mein",
        slug: "khel-khel-mein",
        genre: "Comedy, Drama",
        year: 2024,
        img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABeXwD-qEHgU9FL1kF61lyVf8Ir_-Af1WFNm0X3kJfzfA7fqRx04IdC4Ydxen-mkUw0LSunAMuAC8kR2nNEWiE0pAv3YvlsRajM22kTaA_7H4_f-PXVkSSB2pcuoEpofQvKXHZZmRPU9rQovLwYa7jVP5glo5ZwlhwEbJVRsc3DXLbcbLWb8k0Y5wIp4kl6IgAP6iMIHdSfT3TF8CP3HEZg6y7rkLfPYaeKDpuZTLWaQ1HHtoo-jYrGPpJwF4LoAuhU7bMeSp8vj1l97ZFfkCUopDwpx28g.webp?r=285",
        description: "Revolves around a group of friends who gather for a dinner and end up revealing secrets about each other.",
        rating: "U/A 16+",
        actors: ["Akshay Kumar", "Ammy Virk", "Taapsee Pannu"],
        director: "Mudassar Aziz",
        youtube_trailer: "url_to_trailer_of_khel_khel_mein"
      },
      {
        id: 8,
        title: "Khel Khel Mein",
        slug: "khel-khel-mein",
        genre: "Comedy, Drama",
        year: 2024,
        img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABUuMADIinIAknUXHOcERf4kE_q37PTwfK28bj0CIRRGJKNC2WA9L4rQoUebai2BzUmeA8vkKiZaQrpIIFOwTogS5aSjJKdWX1u_O.webp?r=3f0",
        description: "Revolves around a group of friends who gather for a dinner and end up revealing secrets about each other.",
        rating: "U/A 16+",
        actors: ["Akshay Kumar", "Ammy Virk", "Taapsee Pannu"],
        director: "Mudassar Aziz",
        youtube_trailer: "url_to_trailer_of_khel_khel_mein"
      },
      {
        id: 9,
        title: "Khel Khel Mein",
        slug: "khel-khel-mein",
        genre: "Comedy, Drama",
        year: 2024,
        img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABRdGDVBp34YaKFc1iSbx7xY_gRumZABWCTDA7l-XTt8S-B12c4-QWOEBjkqEro25QnCqe0bl-sfcEmSAc7Y-Jp2U4NV83WpXM8n6VgJFa2hlcpjOZyIMKI9d_CCeybVnQudURI6EyUTHwceSzvoBAx0itnzyn015ZCpQnUOMWG0sq_v1cm15tyMg2OGeUXHJbvzsFEvUEwKx-ZbfQs0U0qY2KGxJV7wGv11bBk1TPAAuw0ugM0uVS8j5nKI9jzw7G8B232p3v1tIM60ONbru-qIe8R91MQ.webp?r=3dd",
        description: "Revolves around a group of friends who gather for a dinner and end up revealing secrets about each other.",
        rating: "U/A 16+",
        actors: ["Akshay Kumar", "Ammy Virk", "Taapsee Pannu"],
        director: "Mudassar Aziz",
        youtube_trailer: "url_to_trailer_of_khel_khel_mein"
      },
      {
        id: 10,
        title: "Khel Khel Mein",
        slug: "khel-khel-mein",
        genre: "Comedy, Drama",
        year: 2024,
        img: "https://occ-0-4857-2186.1.nflxso.net/dnm/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABfpbgMjxJ8vAahQ7324y4FCkHJ70Qpfq5Uab_EG5dnmTh3UJ6AdVq4DFaj49cKo80r9aDZu5hBLcqiBuEaVy3Jzb9JL2X-iyMZThcARh6dx-2N8PyYm6uTzUJMdNkyHIjJw0jUk9N1Je5K7ekWK828eHMpVUjC50UoIcvElaREhz6vEAaPW-c5oamxbiCxRVSWQtcv87s3JTUeohm4MDUrlvd0E36VydyLTavbKGB-JLqCnG8umTrsOWnlMDsiW3rjlmZa5nZI4RiPqFgxowd2_kblHUDw.webp?r=aa4",
        description: "Revolves around a group of friends who gather for a dinner and end up revealing secrets about each other.",
        rating: "U/A 16+",
        actors: ["Akshay Kumar", "Ammy Virk", "Taapsee Pannu"],
        director: "Mudassar Aziz",
        youtube_trailer: "url_to_trailer_of_khel_khel_mein"
      },
  ];

export default movies;

